<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
<<<<<<< HEAD
	<testsuite errors="0" failures="0" name="webpoll.tests.HomeTests-20220128031108" skipped="0" tests="1" time="0.008">
		<testcase classname="webpoll.tests.HomeTests" name="test_home" time="0.008"/>
=======
	<testsuite errors="1" failures="0" name="webpoll.tests.HomeTests-20220128025722" skipped="0" tests="1" time="0.003">
		<testcase classname="webpoll.tests.HomeTests" name="test_home" time="0.003">
			<error message="Reverse for 'home' not found. 'home' is not a valid view function or pattern name." type="NoReverseMatch">
<![CDATA[Traceback (most recent call last):
  File "/projects/challenge/webpoll/tests.py", line 6, in test_home
    response=self.client.get(reverse('home'))
  File "/home/user/.local/lib/python3.5/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/user/.local/lib/python3.5/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
]]>			</error>
		</testcase>
>>>>>>> 804f34e43929fb617525e2098d79c87e5fb050da
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testsuite>
</testsuites>
